import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Galano Grotesque"', "system-ui", "sans-serif"],
        display: ['Fraunces', "Georgia", "serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      spacing: {
        gutter: "36px",
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "8": "32px",
        "10": "40px",
        "12": "48px",
        "16": "64px",
        "20": "80px",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Lumina brand scales — full 50–900 ramps
        orange: {
          50:  "hsl(var(--orange-50))",
          100: "hsl(var(--orange-100))",
          200: "hsl(var(--orange-200))",
          300: "hsl(var(--orange-300))",
          400: "hsl(var(--orange-400))",
          500: "hsl(var(--orange-500))",
          600: "hsl(var(--orange-600))",
          700: "hsl(var(--orange-700))",
          800: "hsl(var(--orange-800))",
          900: "hsl(var(--orange-900))",
        },
        yellow: {
          50:  "hsl(var(--yellow-50))",
          100: "hsl(var(--yellow-100))",
          200: "hsl(var(--yellow-200))",
          300: "hsl(var(--yellow-300))",
          400: "hsl(var(--yellow-400))",
          500: "hsl(var(--yellow-500))",
          600: "hsl(var(--yellow-600))",
          700: "hsl(var(--yellow-700))",
          800: "hsl(var(--yellow-800))",
          900: "hsl(var(--yellow-900))",
        },
        coral: {
          50:  "hsl(var(--coral-50))",
          100: "hsl(var(--coral-100))",
          200: "hsl(var(--coral-200))",
          300: "hsl(var(--coral-300))",
          400: "hsl(var(--coral-400))",
          500: "hsl(var(--coral-500))",
          600: "hsl(var(--coral-600))",
          700: "hsl(var(--coral-700))",
          800: "hsl(var(--coral-800))",
          900: "hsl(var(--coral-900))",
        },
        sage: {
          50:  "hsl(var(--sage-50))",
          100: "hsl(var(--sage-100))",
          200: "hsl(var(--sage-200))",
          300: "hsl(var(--sage-300))",
          400: "hsl(var(--sage-400))",
          500: "hsl(var(--sage-500))",
          600: "hsl(var(--sage-600))",
          700: "hsl(var(--sage-700))",
          800: "hsl(var(--sage-800))",
          900: "hsl(var(--sage-900))",
        },
        teal: {
          50:  "hsl(var(--teal-50))",
          100: "hsl(var(--teal-100))",
          200: "hsl(var(--teal-200))",
          300: "hsl(var(--teal-300))",
          400: "hsl(var(--teal-400))",
          500: "hsl(var(--teal-500))",
          600: "hsl(var(--teal-600))",
          700: "hsl(var(--teal-700))",
          800: "hsl(var(--teal-800))",
          900: "hsl(var(--teal-900))",
        },
        sky: {
          50:  "hsl(var(--sky-50))",
          100: "hsl(var(--sky-100))",
          200: "hsl(var(--sky-200))",
          300: "hsl(var(--sky-300))",
          400: "hsl(var(--sky-400))",
          500: "hsl(var(--sky-500))",
          600: "hsl(var(--sky-600))",
          700: "hsl(var(--sky-700))",
          800: "hsl(var(--sky-800))",
          900: "hsl(var(--sky-900))",
        },
        plum: {
          50:  "hsl(var(--plum-50))",
          100: "hsl(var(--plum-100))",
          200: "hsl(var(--plum-200))",
          300: "hsl(var(--plum-300))",
          400: "hsl(var(--plum-400))",
          500: "hsl(var(--plum-500))",
          600: "hsl(var(--plum-600))",
          700: "hsl(var(--plum-700))",
          800: "hsl(var(--plum-800))",
          900: "hsl(var(--plum-900))",
        },
        // Lumina semantic status surfaces
        "success-surface": {
          DEFAULT: "hsl(var(--success-bg))",
          foreground: "hsl(var(--success-text))",
          border: "hsl(var(--success-border))",
        },
        "risk-surface": {
          DEFAULT: "hsl(var(--risk-bg))",
          foreground: "hsl(var(--risk-text))",
          border: "hsl(var(--risk-border))",
        },
        "warning-surface": {
          DEFAULT: "hsl(var(--warning-bg))",
          foreground: "hsl(var(--warning-text))",
          border: "hsl(var(--warning-border))",
        },
        "info-surface": {
          DEFAULT: "hsl(var(--info-bg))",
          foreground: "hsl(var(--info-text))",
          border: "hsl(var(--info-border))",
        },
        "ai-surface": {
          DEFAULT: "hsl(var(--ai-bg))",
          foreground: "hsl(var(--ai-text))",
          border: "hsl(var(--ai-border))",
        },
        // LMP Dark palette — used inside .dark for analytics surfaces
        d: {
          bg:       "hsl(var(--d-bg))",
          surface1: "hsl(var(--d-surface-1))",
          surface2: "hsl(var(--d-surface-2))",
          border:   "hsl(var(--d-border))",
          text:     "hsl(var(--d-text))",
          muted:    "hsl(var(--d-muted))",
          blue:     "hsl(var(--d-blue))",
          green:    "hsl(var(--d-green))",
          amber:    "hsl(var(--d-amber))",
          red:      "hsl(var(--d-red))",
          purple:   "hsl(var(--d-purple))",
        },
        n50:  "hsl(var(--n50))",
        n100: "hsl(var(--n100))",
        n200: "hsl(var(--n200))",
        n300: "hsl(var(--n300))",
        n400: "hsl(var(--n400))",
        n500: "hsl(var(--n500))",
        n600: "hsl(var(--n600))",
        n700: "hsl(var(--n700))",
        n800: "hsl(var(--n800))",
        n900: "hsl(var(--n900))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        /* Lumina semantic tokens — prefer these in new code */
        control: "var(--radius)",           /* 8px — buttons, inputs, filters, chips */
        card:    "var(--radius-card)",      /* 16px — cards, bento blocks, tables */
        modal:   "var(--radius-modal)",     /* 12px — modals, drawers, popovers */
        pill:    "var(--radius-pill)",      /* 9999px — status badges, tags */
        /* Tailwind scale (aligned to Lumina) */
        "2xl": "16px",
        xl:    "12px",
        lg:    "8px",   /* controls — was incorrectly 16px */
        md:    "8px",
        sm:    "6px",
        xs:    "4px",
      },
      backgroundImage: {
        "grad-mu":      "var(--grad-mu)",
        "grad-new":     "var(--grad-new)",
        "grad-ai-aura": "var(--grad-ai-aura)",
        "grad-feature": "var(--grad-feature)",
        "grad-yellow":  "var(--grad-yellow)",
        "grad-blue":    "var(--grad-blue)",
        "grad-green":   "var(--grad-green)",
        "grad-text":    "var(--lx-grad-text)",
        "sidebar-warm-dark": "var(--sidebar-gradient)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        focus: "var(--focus-ring)",
        "ai-ring": "0 0 0 4px rgba(227,131,48,0.10)",
      },
      transitionTimingFunction: {
        smooth: "cubic-bezier(.4,0,.2,1)",
        enter:  "cubic-bezier(0,0,.2,1)",
        exit:   "cubic-bezier(.4,0,1,1)",
        spring: "cubic-bezier(.34,1.56,.64,1)",
      },
      maxWidth: {
        content: "1280px",
        dashboard: "1140px",
        prose: "680px",
        form: "480px",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to:   { opacity: "1", transform: "scale(1)" },
        },
        "shimmer": {
          "0%":   { backgroundPosition: "0% 50%" },
          "100%": { backgroundPosition: "200% 50%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 220ms cubic-bezier(0,0,.2,1)",
        "scale-in": "scale-in 350ms cubic-bezier(0,0,.2,1)",
        "shimmer": "shimmer 2.4s linear infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
