// Versioned permission contract consumed by both the frontend and Edge Functions.
export const PERMISSION_CONTRACT_VERSION = "2026-06-11.2";
export const VIEW_AS_READ_ONLY = true;

export type ContractRole = "admin" | "allocator" | "poc";

export const ACTION_MATRIX = {
  view_all_lmps: ["admin", "allocator"],
  view_own_lmps: ["admin", "allocator", "poc"],
  view_other_poc_lmps_summary: ["admin", "allocator", "poc"],
  create_lmp: ["admin", "allocator"],
  edit_lmp: ["admin", "allocator", "poc"],
  delete_lmp: ["admin", "allocator", "poc"],
  assign_poc: ["admin", "allocator"],
  reassign_poc: ["admin", "allocator"],
  assign_mentor: ["admin", "allocator", "poc"],
  run_mentor: ["admin", "allocator", "poc"],
  change_domain: ["admin", "allocator"],
  change_status: ["admin", "allocator", "poc"],
  edit_daily_progress: ["admin", "allocator", "poc"],
  edit_prep_status: ["admin", "allocator", "poc"],
  edit_mentor_status: ["admin", "allocator", "poc"],
  edit_mock_status: ["admin", "allocator", "poc"],
  edit_assignment_review: ["admin", "allocator", "poc"],
  edit_outreach_progress: ["admin", "allocator", "poc"],
  edit_remarks: ["admin", "allocator", "poc"],
  edit_checklist: ["admin", "allocator", "poc"],
  edit_next_progress: ["admin", "allocator", "poc"],
  add_candidate: ["admin", "allocator", "poc"],
  remove_candidate: ["admin", "allocator", "poc"],
  update_candidate_stage: ["admin", "allocator", "poc"],
  update_session: ["admin", "allocator", "poc"],
  add_feedback: ["admin", "allocator", "poc"],
  add_activity_comment: ["admin", "allocator", "poc"],
  upload_jd: ["admin", "allocator", "poc"],
  bulk_update: ["admin"],
  view_all_students: ["admin", "allocator", "poc"],
  view_own_students: ["admin", "allocator", "poc"],
  view_all_pocs: ["admin", "allocator"],
  view_poc_load: ["admin", "allocator"],
  manage_users: ["admin"],
  manage_rbac: ["admin"],
  view_settings: ["admin"],
  view_audit_logs: ["admin"],
  view_sync_logs: ["admin"],
  view_field_mapping: ["admin"],
  edit_field_mapping: ["admin"],
  rollback_any: ["admin"],
  rollback_own: ["admin", "allocator", "poc"],
  rollback_managed: ["admin", "allocator"],
  copilot_summarize: ["admin", "allocator", "poc"],
  copilot_search: ["admin", "allocator", "poc"],
  copilot_analyze: ["admin", "allocator", "poc"],
  copilot_draft_update: ["admin", "allocator", "poc"],
  copilot_execute_update: ["admin", "allocator", "poc"],
  view_domains: ["admin", "allocator", "poc"],
  edit_domains: ["admin", "allocator"],
  view_unmapped: ["admin", "allocator", "poc"],
  resolve_unmapped: ["admin"],
  allocate_poc: ["admin", "allocator"],
} as const satisfies Record<string, readonly ContractRole[]>;

export const FIELD_PERMISSIONS = {
  company: { editable: ["admin", "allocator"], requiresOwnership: false },
  role: { editable: ["admin", "allocator"], requiresOwnership: false },
  domain: { editable: ["admin", "allocator"], requiresOwnership: false },
  status: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  type: { editable: ["admin", "allocator"], requiresOwnership: false },
  date: { editable: ["admin", "allocator"], requiresOwnership: false },
  closing_date: { editable: ["admin", "allocator"], requiresOwnership: false },
  admin_owner: { editable: ["admin"], requiresOwnership: false },
  allocator: { editable: ["admin"], requiresOwnership: false },
  prep_poc: { editable: ["admin", "allocator"], requiresOwnership: false },
  support_poc: { editable: ["admin", "allocator"], requiresOwnership: false },
  outreach_poc: { editable: ["admin", "allocator"], requiresOwnership: false },
  daily_progress: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  prep_progress: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  placement_progress: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  r1_shortlisted: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  r2_shortlisted: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  r3_shortlisted: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  final_convert: { editable: ["admin", "allocator"], requiresOwnership: false },
  convert_names: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  prep_doc: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  remarks: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  mentor_aligned: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  assignment_review: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  one_to_one_mock: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
  behavioral_status: { editable: ["admin", "allocator", "poc"], requiresOwnership: true },
} as const;

export const POC_WRITABLE_LMP_COLUMNS = [
  "company", "role",
  "daily_progress", "prep_progress", "placement_progress",
  "next_progress_date", "next_progress_status", "next_progress_type",
  "next_progress_reminder_type", "last_progress_updated_at",
  "remarks", "mentor_aligned", "prep_doc_shared", "assignment_review",
  "one_to_one_mock", "behavioral_status", "status", "r1_shortlisted", "r2_shortlisted",
  "r3_shortlisted", "convert_names", "prep_doc",
] as const;
